### ISSUE TITLE
Calc returns 0px, but expected to be 0 with no units

### ISSUE THREAD

**Issue by hawckins** [postcss/postcss-calc#92] opened 2019-09-27 16:26 UTC
We have a stylelint "length-zero-no-unit":true enabled so 0 values should not have units associated to it. But calc is returning 0 with units for example calc(2px * 0); is returning as 0px but if zero we need just 0 not 0px. Is there any option which I can enable to get this?

**Comment by evilebottnawi** [comment] 2019-09-27 16:40
How it is related to postcss-calc?

**Comment by evilebottnawi** [comment] 2019-09-27 16:40
Also `length-zero-no-unit` is ignored calc in new version of stylelint, because it was bug, please update stylelint

**Comment by tannerdolby** [comment] 2023-05-05 04:22
From my understanding, unitless zero lengths inside `calc()` are not valid as 0 cannot be treated as a valid [`<length>`](https://drafts.csswg.org/css-values-3/#lengths) and the expected behavior of `calc(10px * 0)` should evaluate to `0px`. In terms of parsers, someone could write parsing logic to force a unitless zero length to be spit out e.g. 0 instead of 0px but I don't think that's a very good idea just to avoid a stylelint rule.

- https://lists.w3.org/Archives/Public/www-style/2010Dec/0479.html
- https://drafts.csswg.org/css-values-3/#calc-notation

**Comment by ludofischer** [comment] 2023-05-05 11:48
I take it that this was never a cssnano issue but rather a mistaken rule in an (old) stylelint release, so we can close it.

**Closed by ludofischer** 2023-05-05 11:48 UTC
Labels: enhancement
