### ISSUE TITLE
Space between multiplication and division operators is clamped with custom properties

### ISSUE THREAD

**Issue by joneff** [postcss/postcss-calc#127] opened 2020-12-23 09:59 UTC
Using postcss-calc v7.0.5

```css
/* Input */
.selector {
    bottom: calc( var(--a, 0) * 1% );
    height: calc( (var(--b, 0) - var(--a, 0)) * 1% );
}

/* output */
.selector {
    bottom: calc(var(--a, 0)*1%);
    height: calc((var(--b, 0) - var(--a, 0))*1%);
}
```

While multiplication and division still work, various tools are reporting it is invalid.

**Comment by ludofischer** [comment] 2022-01-09 20:21
If the output works, wouldn't this be an issue with the tools that report it as invalid, rather then postcss-calc?

**Comment by ludofischer** [comment] 2022-01-09 20:36
The spec mentions that space around the multiplication and division operator is not required: https://drafts.csswg.org/css-values/#calc-syntax

**Comment by ludofischer** [comment] 2022-01-09 20:49
Since the output conforms to the spec and works as expected, I would close this as not a bug in postcss-calc.

**Closed by ludofischer** 2022-01-09 20:49 UTC
