### ISSUE TITLE
Support min, max, clamp

### ISSUE THREAD

**Issue by depoulo** [postcss/postcss-calc#123] opened 2020-11-04 10:39 UTC
See also #117.

See https://developer.mozilla.org/en-US/docs/Web/CSS/clamp

It would really suck if I cannot use min, max, and clamp, even though current browsers support them, just because the PostCSS transform does not (in my setup I'm using this transform to serve legacy browsers).
Happy to give it a go myself if you signal that you'd be willing to add this.

**Comment by evilebottnawi** [comment] 2020-11-04 11:56
PR welcome

**Comment by ludofischer** [comment] 2022-01-09 20:22
Duplicate of #117

**Closed by ludofischer** 2022-01-09 20:22 UTC
